### ISSUE TITLE
Any statistical considerations behind the choice of 'valid_size', and 'test_size'?

### ISSUE THREAD

**Issue by ahwatnow** [ShengranHu/ADAS#18]
Hello,

First of all, I want to say how much I admire the incredible work your team has done! I'm really excited about the direction your team proposed with the automatic design of agent systems.

I have a quick question regarding the **choice of validation and test set sizes**. I've noticed that across different benchmark datasets, the validation set size is mostly set to 128 and the test set size to 800.

I'm curious to know if there are any statistical considerations or reasoning behind these specific numbers, regardless of the dataset.

Thank you.

**Comment by ShengranHu** [comment]
Thank you for your comment and your kind words on our work! We did not have rigorous statistical considerations behind those numbers. The numbers are set based on the engineering insights from our empirical study to balance the cost and accuracy of evaluation. But I do believe further analysis on it will be interesting if you are interested in this parameter choice (which is also a common parameter in other autoML areas like NAS).

**Comment by ahwatnow** [comment]
Thank you for your quick reply and the insights! I wanted to make sure before we run multiple experiments.
