### ISSUE TITLE
"response_json" misspelled as "reponse_json" (missing s) in many places

### ISSUE THREAD

**Issue by timdingman-scale** [ShengranHu/ADAS#3]
Certainly in class LLMAgentBase() in search.py in _mmlu, which I'm currently hacking on

**Comment by ShengranHu** [comment]
Thank you for pointing that out! We’ve fixed the typo across the repo in the latest commit https://github.com/ShengranHu/ADAS/commit/03dd85b2aded8a390653ece1abb7ba7e64ae311c.
