### ISSUE TITLE
Location of generated agents?

### ISSUE THREAD

**Issue by anhinga** [ShengranHu/ADAS#4]
Thanks for a super interesting work!

The paper says on page 31: "Here we present the best agent on ARC discovered by Meta Agent Search. All agents from the
experiment can be found at https://github.com/ShengranHu/ADAS."

But I don't seem to be able to locate the generated agents. I wonder if they are missing from the repository. (What I am really trying to find is the three agents mentioned on the last three lines of Table 2, Section 4.3, page 9, especially the "Dynamic Memory and Refinement Agent".)

**Comment by ShengranHu** [comment]
Hello, thanks for your interest in our work! The generated agents are located in the [result](https://github.com/ShengranHu/ADAS/tree/main/results) folder. 

Regarding the specific agent you’re looking for (Dynamic Memory and Refinement Agent) you can find it [here](https://github.com/ShengranHu/ADAS/blob/main/results/arc_gpt3.5_results.json#L100) under a different name. As mentioned in the paper, this agent originally had a confusing name, so we manually renamed it. You will find it listed as the “Meta-Learning Agent” from generation 8.

**Comment by anhinga** [comment]
Thanks a lot!
